Update webcam to make more sense
webcam now does the same thing whether run with or without -q.
Not passing -q just runs the mpv client, all other behaviour is now
identical. Calling webcam without -q when client is running closes the
client instead of a useless (too userfriendly) notify.

Other changes:
- now uses $? to get error codes instead of using variables
- increased delay to 2.5 seconds to overcome cold starts
- added documentation
- changed order of checking phone present and phone locked

diff --git a/webcam b/webcam
--- a/webcam
+++ b/webcam
@@ -1,60 +1,47 @@
 #!/bin/bash
-if [ -e ~/.cache/webcam.lock ]
+if [ -e ~/.cache/webcam.lock ] # if client is already running
 then
-	if [ "$1" != "-q" ]
-	then
-		notify-send -h string:desktop-entry:droidcam -i camera-ready.svg -a "Webcam" "Camera already on" "$HOME/.cache/webcam.lock exists"
-		 exit 0
-	else
-		killall mpv
-		killall droidcam-cli
-		adb shell am force-stop com.dev47apps.droidcam
-		killall mpv
-		rm ~/.cache/webcam.lock -f
-		notify-send -h string:desktop-entry:droidcam -i camera-off.svg -a "Webcam" "Camera client killed"
-		exit 0
-	fi
+	killall mpv
+	killall droidcam-cli	# kill client
+	adb shell am force-stop com.dev47apps.droidcam # kill client from mobile
+	killall mpv		# sometimes needed to be done twice
+	rm ~/.cache/webcam.lock -f # remove flag file
+	notify-send -h string:desktop-entry:droidcam -i camera-off.svg -a "Webcam" "Camera client killed"
+	exit 0
 fi
 
+# start adb port forwarding from phone to pc
+adb forward tcp:4747 tcp:4747 
+if [ "$?" != "0" ]	# if failed to forward, notify and exit
+then
+	notify-send -i camera-off.svg -a "Webcam" "ADB port forwarding failed!" -h string:desktop-entry:droidcam
+	exit 1
+fi
+
+# if phone is locked notify and exit
 if [ "$(adb shell dumpsys power | grep 'Screen off timeout' | awk '{print $4}')" = "10000" ] 
 then
 	notify-send -h string:desktop-entry:droidcam -i camera-off.svg -a "Webcam" "Phone is locked"
 	exit 1
 fi
 
-fwd=1
-adb forward tcp:4747 tcp:4747 || fwd=0
-if [ $fwd = 0 ]
-then
-	 notify-send -i camera-off.svg -a "Webcam" "ADB port forwarding failed!" -h string:desktop-entry:droidcam
-	 exit 1
-fi
-
-app=1
-adb shell monkey -p com.dev47apps.droidcam 1 || app=0
-if [ $app = 0 ]
+# start droidcam app in phone
+adb shell monkey -p com.dev47apps.droidcam 1 
+if [ "$?" != "0" ]	# if unable to start, notify and exit
 then
 	 notify-send -i camera-off.svg -a "Webcam" "Droidcam app not installed!" -h string:desktop-entry:droidcam
 	 exit 1
 fi
 
-
-
 notify-send -t 3000 -i camera-on.svg -a "Webcam" "Webcam ON" -h string:desktop-entry:droidcam
-touch ~/.cache/webcam.lock
+touch ~/.cache/webcam.lock # create flag file
 
 # to allow app to launch, delay for a few seconds
-sleep 2
-
+sleep 2.5
+# start the droidcam client
 droidcam-cli 0.0.0.0 4747 </dev/null  &>/dev/null & 
 
-if [ "$1" != "-q" ]
+if [ "$1" != "-q" ] # if not run quietly open mpv
 then
-
-	mpv --no-audio --untimed --profile=low-latency --ontop --force-window=immediate --on-all-workspaces --geometry=100%:100% --autofit=400 --cursor-autohide=no --no-input-cursor --osd-on-seek=no --vf=hflip av://v4l2:/dev/video0
-
-	#after streaming ends
-	killall droidcam-cli
-	adb shell am force-stop com.dev47apps.droidcam
-	rm ~/.cache/webcam.lock
+	mpv --no-audio --untimed --profile=low-latency --ontop --force-window=immediate --on-all-workspaces --geometry=100%:100% --autofit=400 --cursor-autohide=no --no-input-cursor --osd-on-seek=no --vf=hflip av://v4l2:/dev/video0 &
 fi
