💯th commit: modularize, beautify, and document yt
- added dependency list at top of program
- created variables for default prompt program and gui prompt program
  so that changing the programs is easy.
- replace hardcoded 'rofi' in search input to $guicmd
- check if able to fetch youtube result page, if not then inform and exit
- modularize grepping the response for video and playlist entries
- store the ids in pattern: id \t (type) title
- show the title only (not id) to the prompt cmd, then grep the choice
  from the id list to get corresponding id
- added documentation

diff --git a/yt b/yt
--- a/yt
+++ b/yt
@@ -1,18 +1,22 @@
 #!/bin/bash
+# dependencies: mpv youtube-dl fzf rofi/dmenu
 # search videos and playlists on youtube and play them in mpv, without an API 
 # usage:
 # yt					asks for input in stdin, prompts using fzf
 # yt search query		takes input from the passed arg, prompts using fzf
-# yt -r					takes input and prompts using rofi
+# yt -r					takes input and prompts using rofi ($guicmd)
 
-promptcmd="fzf --with-nth=2..-1"
+defcmd="fzf"
+guicmd="rofi -dmenu -i" #uncomment next line for dmenu
+#guicmd="dmenu -i -l 15"
+promptcmd="$defcmd"
 if [ -z "$*" ]; then 
 	echo -n "Search: "
 	read -r query
 else
 	case "$1" in
-		-r) query=$(rofi -dmenu -p "Search: ")
-			promptcmd="rofi -dmenu -no-custom -p Video:";;
+		-r) query=$(echo | $guicmd -p "Search: ")
+			promptcmd="$guicmd -p Video:";;
 		*) query="$*";;
 	esac
 fi
@@ -25,45 +29,41 @@ query=$(sed \
 	-e 's| |+|g'\
 	<<< "$query")
 # fetch the results with the $query 
-response=$(curl -s "https://www.youtube.com/results?search_query=$query")
+response="$(curl -s "https://www.youtube.com/results?search_query=$query")"
+# if unable to fetch the youtube results page, inform and exit
+if ! grep -q "script" <<< "$response"; then echo "unable to fetch yt"; exit 1; fi
+# regex expression to match video and playlist entries from yt result page
 vgrep='"videoRenderer":{"videoId":"\K.{11}".+?"text":".+?[^\\](?=")'
 pgrep='"playlistRenderer":{"playlistId":"\K.{34}?","title":{"simpleText":".+?[^\"](?=")'
-# grep the video id and title
-# replace " with “ so that entire title is displayed even if it has "
-videoids=$(
-	echo "$response" | \
-	grep -oP "$vgrep" | \
-	sed 's|\\\"|“|g' | \
-	awk -F\" '{ print $1 "\t\t\t\t" $NF}'
-)
-# grep the playlist id and title
-# replace " with “ so that entire title is displayed even if it has "
-playlistids=$(
-	echo "$response" | \
-	grep -oP "$pgrep" | \
-	sed 's|\\\"|“|g' | \
-	awk -F\" '{ print $1 "\t(playlist) " $NF }'
-)
-# if there are playlists, append them to list
+# grep the id and title
+# replace \" with “ so that entire title is displayed even if it has "
+# return them in format id (type) title
+getresults() {
+	grep -oP "$1" <<< "$response" | sed 's|\\\"|“|g' | \
+		awk -F\" -v p="$2" '{ print $1 "\t" p " " $NF}'
+}
+# get the list of videos/playlists and their ids in videoids and playlistids
+videoids=$(getresults "$vgrep")
+playlistids=$(getresults "$pgrep" "(playlist)")
+# if there are playlists or videos, append them to list
 [ -n "$playlistids" ] && ids="$playlistids\n"
-# if there are videos, append them to list
 [ -n "$videoids" ] && ids="$ids$videoids"
 # url prefix for videos and playlists
 videolink="https://youtu.be/"
 playlink="https://youtube.com/playlist?list="
 # prompt the results to user infinitely until they exit (escape)
 while true; do
-	id=$(
-		echo -e "$ids" | \
-		$promptcmd | \
-		cut -d'	' -f1
-	)
+	clear
+	echo "Choose Video/Playlist to play: "
+	choice=$(echo -e "$ids" | cut -d'	' -f2 | $promptcmd) # dont show id
+	if [ -z "$choice" ]; then exit; fi	# if esc-ed then exit
+	id=$(echo -e "$ids" | grep -wm1 "$choice" | cut -d'	' -f1) # get id of choice
+	echo -e "$choice\t($id)"
 	case $id in
 		# 11 digit id = video
 		???????????) mpv "$videolink$id";;
 		# 34 digit id = playlist
 		??????????????????????????????????) mpv "$playlink$id";;
-		"") exit ;;
-		*) echo "invalid id - $id" ;;
+		*) exit ;;
 	esac
 done
